# file: roles/commons/tasks/main.yml

- name: Common | Make sure some basic tools are installed
  apt: pkg={{ item }}
  with_items:
    - command-not-found
    - curl
    - debconf
    - dmidecode
    - htop
    - dstat
    - iftop
    - iotop
    - nmap
    - mosh
    - pciutils
    - sysstat
    - tmux
    - tshark
    - pssh
    - pbzip2
    - xfsprogs
    - s3cmd

- name: Common | Make sure git is installed
  apt: pkg=git

- name: Common | Make sure encfs and dependencies are installed
  apt: pkg={{ item }}
  with_items:
    - encfs
    - libfuse-dev
    - fuse-utils
